spring:
  application:
    name: ecommerce-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: ecommerce
        
logging:
  level:
    root: INFO
    com.ecommerce.ecommercebackend: INFO