package com.ecommerce.ecommercebackend.service.auth.impl;

import com.ecommerce.ecommercebackend.config.JwtProperties;
import com.ecommerce.ecommercebackend.exception.TokenRefreshException;
import com.ecommerce.ecommercebackend.model.auth.RefreshToken;
import com.ecommerce.ecommercebackend.model.user.User;
import com.ecommerce.ecommercebackend.repository.auth.RefreshTokenRepository;
import com.ecommerce.ecommercebackend.repository.user.UserRepository;
import com.ecommerce.ecommercebackend.service.auth.RefreshTokenService;
import java.time.Instant;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of the RefreshTokenService. Handles the actual database transactions and business
 * logic for the lifecycle of refresh tokens.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class RefreshTokenServiceImpl implements RefreshTokenService {

    private final RefreshTokenRepository refreshTokenRepository;
    private final UserRepository userRepository;
    private final JwtProperties jwtProperties;

    /**
     * Creates and saves a new refresh token record in the database after a successful login.
     *
     * @param userId The ID of the authenticated user.
     * @param token The actual JWT string generated by JwtTokenProvider.
     * @return The saved RefreshToken entity.
     */
    @Override
    @Transactional
    public RefreshToken saveRefreshTokenEntity(Long userId, String token) {
        User user = userRepository
                .findById(userId)
                .orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));

        RefreshToken refreshToken = new RefreshToken();
        refreshToken.setUser(user);
        refreshToken.setToken(token);

        // Sync the DB expiration time directly with the application.yml configuration
        refreshToken.setExpiryDate(Instant.now().plusMillis(jwtProperties.getRefreshTokenExpiration()));
        refreshToken.setActive(true); // Token is valid upon creation

        return refreshTokenRepository.save(refreshToken);
    }

    /** Retrieves a token entity from the database using the raw JWT string. */
    @Override
    public Optional<RefreshToken> findByToken(String tokenString) {
        return refreshTokenRepository.findByToken(tokenString);
    }

    /**
     * Core security check. Verifies if the token exists, is active, and hasn't expired. If it has
     * expired, it defensively updates the status to inactive (revoked) in the DB. Throws a custom
     * TokenRefreshException if validation fails.
     *
     * @param token The RefreshToken entity retrieved from the database.
     * @return The validated RefreshToken entity.
     */
    @Override
    @Transactional
    public RefreshToken verifyExpirationAndStatus(RefreshToken token) {
        // Check 1: Is it manually revoked (e.g., user logged out)?
        if (!token.isActive()) {
            throw new TokenRefreshException("This refresh token has been revoked. Please log in again.");
        }

        // Check 2: Has the time expired?
        if (token.getExpiryDate().compareTo(Instant.now()) < 0) {
            token.setActive(false);
            refreshTokenRepository.save(token); // Update DB to reflect expired state
            throw new TokenRefreshException("Refresh token has expired. Please make a new login request.");
        }

        return token;
    }

    /**
     * Marks a token as inactive (revoked). Used primarily for Logout functionality.
     *
     * @param tokenString The JWT string to be revoked.
     */
    @Override
    @Transactional
    public void revokeToken(String tokenString) {
        refreshTokenRepository.findByToken(tokenString).ifPresent(token -> {
            token.setActive(false);
            refreshTokenRepository.save(token);
            log.info(
                    "Refresh token revoked successfully for user ID: {}",
                    token.getUser().getId());
        });
    }
}
